In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Afficionado Coffee Roasters.xlsx - Transactions.csv to Afficionado Coffee Roasters.xlsx - Transactions.csv

In [ ]:
import pandas as pd

df = pd.read_csv(list(uploaded.keys())[0])

df.head()

,transaction_id,year,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2025,7:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2025,7:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2025,7:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2025,7:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2025,7:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg

In [ ]:
df.shape

(149116, 11)

In [ ]:
df.columns

Index(['transaction_id', 'year', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail'],
      dtype='object')

In [ ]:
df.isnull().sum()

transaction_id      0
year                0
transaction_time    0
transaction_qty     0
store_id            0
store_location      0
product_id          0
unit_price          0
product_category    0
product_type        0
product_detail      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   year              149116 non-null  int64
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 12.5+ MB

In [ ]:
# Creating Revenue Column for Business Analysis
df['Revenue'] = df['transaction_qty'] * df['unit_price']

In [ ]:
print("Total Revenue =", df['Revenue'].sum())

Total Revenue = 698812.3300000002

In [ ]:
print("Total Quantity Sold =", df['transaction_qty'].sum())

Total Quantity Sold = 214470

In [ ]:
total_transactions = df['transaction_id'].nunique()
print(total_transactions)

149116

In [ ]:
# Checking Number of Transactions by Product Category
df['product_category'].value_counts()

product_category
Coffee                58416
Tea                   45449
Bakery                22796
Drinking Chocolate    11468
Flavours               6790
Coffee beans           1753
Loose Tea              1210
Branded                 747
Packaged Chocolate      487
Name: count, dtype: int64

In [ ]:
# Analyzing Total Revenue Generated by Each Product Category
df.groupby('product_category')['Revenue'].sum().sort_values(ascending=False)

product_category
Coffee                269952.45
Tea                   196405.95
Bakery                 82315.64
Drinking Chocolate     72416.00
Coffee beans           40085.25
Branded                13607.00
Loose Tea              11213.60
Flavours                8408.80
Packaged Chocolate      4407.64
Name: Revenue, dtype: float64

In [ ]:
# Top 10 Best-Selling Products Analysis
df.groupby('product_detail')['transaction_qty'].sum().sort_values(ascending=False).head(10)

product_detail
Earl Grey Rg                   4708
Dark chocolate Lg              4668
Morning Sunrise Chai Rg        4643
Latte                          4602
Peppermint Rg                  4564
Columbian Medium Roast Rg      4547
Traditional Blend Chai Rg      4512
Latte Rg                       4497
Our Old Time Diner Blend Sm    4484
Serenity Green Tea Rg          4477
Name: transaction_qty, dtype: int64

In [ ]:
# Top 10 Revenue Generating Products Analysis
df.groupby('product_detail')['Revenue'].sum().sort_values(ascending=False).head(10)

product_detail
Sustainably Grown Organic Lg    21151.75
Dark chocolate Lg               21006.00
Latte Rg                        19112.25
Cappuccino Lg                   17641.75
Morning Sunrise Chai Lg         17384.00
Latte                           17257.50
Jamaican Coffee River Lg        16481.25
Sustainably Grown Organic Rg    16233.75
Cappuccino                      15997.50
Brazilian Lg                    15109.50
Name: Revenue, dtype: float64

In [ ]:
# Top 10 Least-Selling Products Analysis
df.groupby('product_detail')['transaction_qty'].sum().sort_values().head(10)

product_detail
Dark chocolate                  118
Spicy Eye Opener Chai           122
Guatemalan Sustainably Grown    134
Earl Grey                       142
Jamacian Coffee River           146
Columbian Medium Roast          148
Chili Mayan                     148
Primo Espresso Roast            150
Lemon Grass                     152
Traditional Blend Chai          153
Name: transaction_qty, dtype: int64

In [ ]:
# Top 10 Lowest Revenue Generating Products Analysis
df.groupby('product_detail')['Revenue'].sum().sort_values().head(10)

product_detail
Dark chocolate                   755.20
Earl Grey                       1270.90
Spicy Eye Opener Chai           1335.90
Guatemalan Sustainably Grown    1340.00
Lemon Grass                     1360.40
Peppermint                      1369.35
Traditional Blend Chai          1369.35
English Breakfast               1440.95
Serenity Green Tea              1470.75
Morning Sunrise Chai            1596.00
Name: Revenue, dtype: float64

In [ ]:
import os
os.listdir()

['.config', 'sample_data']

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Afficionado Coffee Roasters.xlsx - Transactions.csv to Afficionado Coffee Roasters.xlsx - Transactions.csv

In [ ]:
import pandas as pd

df = pd.read_csv('Afficionado Coffee Roasters.xlsx - Transactions.csv')

In [ ]:
df.shape

(149116, 11)

In [ ]:
df.columns

Index(['transaction_id', 'year', 'transaction_time', 'transaction_qty',
       'store_id', 'store_location', 'product_id', 'unit_price',
       'product_category', 'product_type', 'product_detail', 'Revenue'],
      dtype='object')

In [ ]:
# Revenue Contribution Analysis by Store Location
df.groupby('store_location')['Revenue'].sum().sort_values(ascending=False)

store_location
Hell's Kitchen     236511.17
Astoria            232243.91
Lower Manhattan    230057.25
Name: Revenue, dtype: float64

In [ ]:
# Sales Volume Analysis by Store Location
df.groupby('store_location')['transaction_qty'].sum().sort_values(ascending=False)

store_location
Lower Manhattan    71742
Hell's Kitchen     71737
Astoria            70991
Name: transaction_qty, dtype: int64

In [ ]:
# Revenue Contribution Analysis by Product Type
df.groupby('product_type')['Revenue'].sum().sort_values(ascending=False).head(10)

product_type
Barista Espresso         91406.20
Brewed Chai tea          77081.95
Hot chocolate            72416.00
Gourmet brewed coffee    70034.60
Brewed Black tea         47932.00
Brewed herbal tea        47539.50
Premium brewed coffee    38781.15
Organic brewed coffee    37746.50
Scone                    36866.12
Drip coffee              31984.00
Name: Revenue, dtype: float64

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Afficionado Coffee Roasters.xlsx - Transactions.csv to Afficionado Coffee Roasters.xlsx - Transactions.csv

In [10]:
# Top Selling Product Types Analysis
df.groupby('product_type')['transaction_qty'].sum().sort_values(ascending=False).head(10)

product_type
Brewed Chai tea          26250
Gourmet brewed coffee    25973
Barista Espresso         24943
Brewed Black tea         17462
Hot chocolate            17457
Brewed herbal tea        17328
Organic brewed coffee    13012
Drip coffee              12891
Premium brewed coffee    12431
Scone                    10465
Name: transaction_qty, dtype: int64

In [11]:
# Pareto Analysis (80/20 Rule)

pareto = df.groupby('product_detail')['Revenue'].sum().reset_index()

pareto = pareto.sort_values(by='Revenue', ascending=False)

pareto['Cumulative_Revenue'] = pareto['Revenue'].cumsum()

pareto['Cumulative_Percentage'] = (
    pareto['Cumulative_Revenue'] / pareto['Revenue'].sum()
) * 100

pareto.head(20)

,product_detail,Revenue,Cumulative_Revenue,Cumulative_Percentage
75,Sustainably Grown Organic Lg,21151.75,21151.75,3.026814
20,Dark chocolate Lg,21006.00,42157.75,6.032771
48,Latte Rg,19112.25,61270.00,8.767733
6,Cappuccino Lg,17641.75,78911.75,11.292266
53,Morning Sunrise Chai Lg,17384.00,96295.75,13.779916
47,Latte,17257.50,113553.25,16.249463
43,Jamaican Coffee River Lg,16481.25,130034.50,18.607929
76,Sustainably Grown Organic Rg,16233.75,146268.25,20.930977
5,Cappuccino,15997.50,162265.75,23.220219
2,Brazilian Lg,15109.50,177375.25,25.382387
31,Ethiopia Lg,14794.50,192169.75,27.499479
21,Dark chocolate Rg,14024.50,206194.25,29.506384
71,Spicy Eye Opener Chai Lg,13652.40,219846.65,31.460042
32,Ethiopia Rg,13179.00,233025.65,33.345956
3,Brazilian Rg,13155.00,246180.65,35.228435
63,Peppermint Lg,13050.00,259230.65,37.095890
26,English Breakfast Lg,12927.00,272157.65,38.945742
23,Earl Grey Lg,12735.00,284892.65,40.768120
68,Serenity Green Tea Lg,12660.00,297552.65,42.579765
14,Columbian Medium Roast Lg,12585.00,310137.65,44.380678

In [12]:
# Products Contributing to 80% Revenue

pareto[pareto['Cumulative_Percentage'] <= 80]

,product_detail,Revenue,Cumulative_Revenue,Cumulative_Percentage
75,Sustainably Grown Organic Lg,21151.75,21151.75,3.026814
20,Dark chocolate Lg,21006.00,42157.75,6.032771
48,Latte Rg,19112.25,61270.00,8.767733
6,Cappuccino Lg,17641.75,78911.75,11.292266
53,Morning Sunrise Chai Lg,17384.00,96295.75,13.779916
47,Latte,17257.50,113553.25,16.249463
43,Jamaican Coffee River Lg,16481.25,130034.50,18.607929
76,Sustainably Grown Organic Rg,16233.75,146268.25,20.930977
5,Cappuccino,15997.50,162265.75,23.220219
2,Brazilian Lg,15109.50,177375.25,25.382387
31,Ethiopia Lg,14794.50,192169.75,27.499479
21,Dark chocolate Rg,14024.50,206194.25,29.506384
71,Spicy Eye Opener Chai Lg,13652.40,219846.65,31.460042
32,Ethiopia Rg,13179.00,233025.65,33.345956
3,Brazilian Rg,13155.00,246180.65,35.228435
63,Peppermint Lg,13050.00,259230.65,37.095890
26,English Breakfast Lg,12927.00,272157.65,38.945742
23,Earl Grey Lg,12735.00,284892.65,40.768120
68,Serenity Green Tea Lg,12660.00,297552.65,42.579765
14,Columbian Medium Roast Lg,12585.00,310137.65,44.380678
78,Traditional Blend Chai Lg,12522.00,322659.65,46.172575
29,Espresso shot,12495.00,335154.65,47.960609
44,Jamaican Coffee River Rg,12455.80,347610.45,49.743033
50,Lemon Grass Lg,12267.00,359877.45,51.498440
58,Our Old Time Diner Blend Lg,11991.00,371868.45,53.214352
24,Earl Grey Rg,11770.00,383638.45,54.898638
12,Civet Cat,11700.00,395338.45,56.572907
10,Chocolate Croissant,11625.98,406964.43,58.236584
54,Morning Sunrise Chai Rg,11607.50,418571.93,59.897617
64,Peppermint Rg,11410.00,429981.93,61.530387
15,Columbian Medium Roast Rg,11367.50,441349.43,63.157075
79,Traditional Blend Chai Rg,11280.00,452629.43,64.771243
69,Serenity Green Tea Rg,11192.50,463821.93,66.372889
59,Our Old Time Diner Blend Rg,11025.00,474846.93,67.950565
51,Lemon Grass Rg,10812.50,485659.43,69.497834
72,Spicy Eye Opener Chai Rg,10636.05,496295.48,71.019852
27,English Breakfast Rg,10500.00,506795.48,72.522401
45,Jamaican Coffee River Sm,9844.10,516639.58,73.931091
33,Ethiopia Sm,9752.60,526392.18,75.326687
4,Brazilian Sm,9482.00,535874.18,76.683561
60,Our Old Time Diner Blend Sm,8968.00,544842.18,77.966881
66,Scottish Cream Scone,8949.45,553791.63,79.247547

In [13]:
len(pareto[pareto['Cumulative_Percentage'] <= 80])

42

In [14]:
df.to_csv('coffee_cleaned_data.csv', index=False)

In [15]:
import os
print(os.listdir())

['.config', 'coffee_cleaned_data.csv', 'Afficionado Coffee Roasters.xlsx - Transactions.csv', 'sample_data']

In [ ]:
from google.colab import files
files.download('filename.ext')